version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export NODE_OPTIONS=--openssl-legacy-provider
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
